### ISSUE TITLE
Feedback (good vibes only)

### ISSUE THREAD

**Issue by MidoriKami** [MidoriKami/Mappy#2]
You can use this issue to post simple feedback, for example mentioning a feature that you particularly liked.

Any negative posts will be deleted, this is for good vibes only. If you have a genuine issue, post it as its own issue.

**Any issues or requests posted here will be ignored, if you have a issue or request post it as its own issue.**

**Comment by iRobsie** [comment]
I love this already. I'm so glad to have an actual modernistic mini-map in the game now, thank you for this. The only thing I think would be a nice addition to what already exists is when you enable "Follower Player", it gave a drop down for like a "Time until Recenter" option so if I move the mini-map away from my character, after X amount of time, it'll snap back to following my character. Or dependent on other options, who knows. I'm just here to say this is great so far and I love it.

**Comment by PrincessRTFM** [comment]
Absolutely never going back to the vanilla map after this. The level of control over what markers are rendered and what's above what, the way FATEs are marked when they're low on time, the fact that I can control how quickly it zooms in and out... this is what a map _should_ be.

The only suggestion/request I have is to make it ignore escape keypresses when focused. Sometimes I'm trying to close other (vanilla) windows and the map receives the escape button instead.

**Comment by CallumCarmicheal** [comment]
This is amazing, I have but one request. Is it possible to see include an option to confirm teleport like in the vanilla map with the price (in the tooltip and popup)? 

This is the only thing I am missing form this.

**Comment by Pipeline929** [comment]
I love the idea of this addon, the only reason I have not fully switched to it is I am unable to look at zones other than the one I am in easily, without having to click on the adjoining zone arrows to navigate around. I may be overlooking the option to do so, but I haven't been able to find it. That's the only request I have and then I would never look back to the default map :D.

**Comment by JSax86** [comment]
Thank you so much for this! I only found the add-on yesterday, but I'm loving it--I actually really wanted a map that I could move to another screen! I actually dragged it over to one of my secondary monitors and sized it to fill the entire thing. It's really cool having that full screen map always available next to the game on the ultrawide. :)

Could you possibly add an option so that Mappy **doesn't** hide during cutscenes or so that it _always_ displays? Since I'm using it on another monitor in the manner that I am, it's rather jarring for me when a cutscene starts and the map disappears!

The ability to customize the background color of the window would also be cool (currently black when you reach the edge of a map).

And also, the option for Follow Player to automatically enable (and snap the map back to your position) after maybe 1-2 seconds of movement would be awesome! I'm a controller player and so my hand isn't on the mouse anymore after I've played around with the map and am ready to get my move on!

Thanks again for this add-on and everything else you work on!

**Comment by KempatchiRamaSamaKun** [comment]
Hi mate,

I notice on my PC that the zone drop-down in the top-left corner is disabled.

Is this something that still needs to be implemented or do I need a plugin to make it work?

Thanks.

**Comment by Matty314** [comment]
Love the plugin, Its hard to locate other areas, If a search function would be possible to add app would go from 10/10 to 100/10

**Comment by MidoriKami** [comment]
> Love the plugin but Its hard to locate other areas, If a search function would be possible to add, plugin would go from 10/10 to 100/10

You mean like the search that's in the toolbar? That recently got improved to be even better?

**Comment by stealyourwife** [comment]
Really like the plugin, but is it possible to cut the Map's X-axis size down even lower? Was hoping that I could cut down the size to at least this much
![image](https://github.com/MidoriKami/Mappy/assets/53972642/abad3afd-4667-4b88-b481-0ae60d7a881d)

**Comment by MidoriKami** [comment]
Locked and unpinned because people are consistently not reading the first post, and instead are posting requests here.
