### ISSUE TITLE
[Request] Add Zoom in / Zoom out buttons plus a couple other ideas

### ISSUE THREAD

**Issue by mgrenier25** [MidoriKami/Mappy#73]
Hey, you guys did great work with this.
Here's a couple ideas to make it even better
1. Could you please add a zoom in and a zoom out button besides the other buttons for us filthy controller players out there :)
2. Maybe I missed it but, show aether currents on the map, either only the undiscovered ones or all of them as icons we could hide after we attuned to them
3. Maybe I missed this one too, show player current coordinates on the map
4. An arrow pointing towards the active quests in the current zone would also be nice

Thats pretty much it.
Oh and why do you say not to use it as a minimap? It's so much better than the original one!!

**Comment by MidoriKami** [comment]
I am currently on a long hiatus from FFXIV and therefore Mappy is not currently accepting feature requests at this time.
I am the sole developer and maintainer of Mappy.

If someone wanted to develop these features and then PR (Pull Request) them to this git repository I would happily review the contribution and then make a release.

Some notes about the posted requests:

1. Mappy was never designed with controller support in mind, to properly support controllers a moderately significant rework of the input system would be required. While zoom in and out buttons would work, it would clutter the UI too much. There have already been several requests in the past to let the Mappy window be a smaller size, and each additional button increases the allowed minimum size.

2. Aether Currents are represented by the game as a GameObject that the server sends to the client, the location of these currents isn't known to the game client until you get near one. This is the same range that enemies will appear on the map. The only way to add Aether Currents would be to hardcode their locations, and that is not something I am willing to do.

3. Player coordinates are shown under the minimap, there is no reason for Mappy to display your current location. When mousing over Mappy's map, the coordinates your cursor is at will be shown in the toolbar.

4. The plugin Aether Compass is a much more elegant solution to this problem, and also addresses request # 2

Mappy can only show markers that I have taught it to show, any new areas or new systems added to the game won't be included in the markers that Mappy knows how to show. There are several places in the game that I never personally played, and thus have not taught Mappy how to show the markers for those areas. If you use Mappy as your only map, you will not see things that you would otherwise be able to see.
